import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("http://localhost:8000/")
    page.get_by_role("link", name="Register").click()
    page.get_by_label("Username*").click()
    page.get_by_label("Username*").press("CapsLock")
    page.get_by_label("Username*").fill("A")
    page.get_by_label("Username*").press("CapsLock")
    page.get_by_label("Username*").fill("Ali")
    page.get_by_label("Password", exact=True).click()
    page.get_by_label("Password", exact=True).fill("ali123456")
    page.get_by_label("Password confirmation").click()
    page.get_by_label("Password confirmation").fill("ali123456")
    page.get_by_role("button", name="Register").click()
    page.get_by_label("Username*").click()
    page.get_by_label("Username*").press("CapsLock")
    page.get_by_label("Username*").fill("A")
    page.get_by_label("Username*").press("CapsLock")
    page.get_by_label("Username*").fill("Ali")
    page.get_by_label("Password*").click()
    page.get_by_label("Password*").fill("ali123456")
    page.get_by_role("button", name="Login").click()
    page.get_by_role("link", name="Create Post").click()
    page.get_by_label("Title*").click()
    page.get_by_label("Title*").fill("ali post")
    page.get_by_label("Content*").click()
    page.get_by_label("Content*").fill("asdfghjk")
    page.get_by_role("button", name="Create Post").click()
    page.get_by_role("link", name="Edit").click()
    page.get_by_label("Title*").click()
    page.get_by_label("Title*").fill("ali post new")
    page.get_by_label("Content*").click()
    page.get_by_label("Content*").fill("asdfghjk new")
    page.get_by_role("button", name="Edit Post").click()
    page.once("dialog", lambda dialog: dialog.dismiss())
    page.get_by_role("link", name="Delete").click()
    page.goto("http://localhost:8000/")
    page.get_by_role("link", name="Create Post").click()
    page.get_by_label("Title*").click()
    page.get_by_label("Title*").press("CapsLock")
    page.get_by_label("Title*").fill("A")
    page.get_by_label("Title*").press("CapsLock")
    page.get_by_label("Title*").fill("ALi")
    page.get_by_label("Content*").click()
    page.get_by_label("Content*").fill("rdfigudhoeilfjre")
    page.get_by_role("button", name="Create Post").click()
    page.get_by_role("link", name="ALi rdfigudhoeilfjre...").click()
    page.get_by_label("Text*").click()
    page.get_by_label("Text*").fill("hihihi")
    page.get_by_role("button", name="Comment").click()
    page.get_by_placeholder("Reply to this comment").click()
    page.get_by_placeholder("Reply to this comment").fill("okoko")
    page.get_by_role("button", name="Post Reply").click()
    page.get_by_role("link", name="Logout").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
